######################################################################
# Automatically generated by qmake (3.0) Tue Jun 21 10:49:12 2016
######################################################################

TEMPLATE = app
TARGET = evdev_trace
INCLUDEPATH += .

DEFINES += _XOPEN_SOURCE=700

QMAKE_CFLAGS += -std=c99

# Input
SOURCES += main.c

